### ISSUE TITLE
Chart design comments

### ISSUE THREAD

**Issue by statist7** [rcpch/digital-growth-charts-react-component-library#2]
The charts look really good. I particularly like the way the centile disjunctions are plotted so clearly, and the BMI units are correctly rendered!

Because they're really good I'm encouraged to be really picky about the design elements. So here's a list of points that strike me:

- add age 0 on the generic age scale, with age units in years/months not y/mths
- in the data entry boxes to the left, make the separate sections more obvious with bold labels for **Reference**, **Birth date**, **Measurement date**, **Measurements**, **Sex** and **Gestation**, each on one line
- when entering a date from the calendar it starts at the date of birth and increments in months - can an option to increment by years be added? Editing the date directly is problematic
- when I go to edit the year in the measurement date box the year first resets to 0000 then the whole date resets to dd/mm/yyyy with an error saying the date is too early - irritating!
- the sex data box is coded male/female but the charts are labelled boys/girls - better to be consistent
- the gestation boxes for weeks and days both need a label
- the height axis is too busy with 5 cm increments - 10 or more would be better. Perhaps aim to have all four charts with a similar number of ticks on the y axis, currently 39 for height, 20 for weight, 6 for BMI and 9 for head circumference
- there is a redundant closing bracket in the BMI axis label
- the preterm data look messy in the generic charts, and it may be better to omit them. Once infant data are entered the age scale changes to represent them correctly, but they don't look right with the age scale unlabelled below 0
- entering a height at age 8 gives the chart from age 4 to 20, but the height scale starts at 0 cm which is wasteful of space - the axis range should be appropriate for the visible chart region, along with a bit more above and below to handle outliers, important particularly for BMI
- this same point applies to the BMI chart, where the y scale could start nearer to 10 than 0. Conversely the head circumference scale perhaps needs to start a bit lower not higher
- with heights of 50 at age 0 and 140 at age 8 the chart displayed is from 4-20 years, with large numbers but no labels on the axes
- plotting weight 4 at age 0 gives a weight axis with no numbers, and the label is weight (cm) !
- adding weight 17 at 40 months adds lollypops to the age axis, but in a large font and no labels
- i don't think the UK-WHO to UK90 transition is flagged on the weight chart in the way it is for height
- the #RoyalColleges3.0 link at the top is hard to see against the background (perhaps deliberately!)

That's probably enough for now...

**Comment by eatyourpeas** [comment]
Thank you! Very helpful comments.
converting these to actions:


- [ ]  add age 0 on the generic age scale, with age units in years/months not y/mths
- [ ] in the data entry boxes to the left, make the separate sections more obvious with bold labels for Reference, Birth date, Measurement date, Measurements, Sex and Gestation, each on one line when entering a date from the calendar it starts at the date of birth and increments in months - can an option to increment by years be added? Editing the date directly is problematic
- [ ] when I go to edit the year in the measurement date box the year first resets to 0000 then the whole date resets to dd/mm/yyyy with an error saying the date is too early - irritating!
- [ ] the sex data box is coded male/female but the charts are labelled boys/girls - better to be consistent
- [ ] the gestation boxes for weeks and days both need a label
- [ ] the height axis is too busy with 5 cm increments - 10 or more would be better. Perhaps aim to have all four charts with a similar number of ticks on the y axis, currently 39 for height, 20 for weight, 6 for BMI and 9 for head circumference
- [ ] there is a redundant closing bracket in the BMI axis label
- [ ] the preterm data look messy in the generic charts, and it may be better to omit them. Once infant data are entered the age scale changes to represent them correctly, but they don't look right with the age scale unlabelled below 0
- [ ] entering a height at age 8 gives the chart from age 4 to 20, but the height scale starts at 0 cm which is wasteful of space
- [ ] the axis range should be appropriate for the visible chart region, along with a bit more above and below to handle outliers, important particularly for BMI
- [ ] this same point applies to the BMI chart, where the y scale could start nearer to 10 than 0. Conversely the head circumference scale perhaps needs to start a bit lower not higher
- [ ] with heights of 50 at age 0 and 140 at age 8 the chart displayed is from 4-20 years, with large numbers but no labels on the axes
- [ ] plotting weight 4 at age 0 gives a weight axis with no numbers, and the label is weight (cm) !
- [ ] adding weight 17 at 40 months adds lollypops to the age axis, but in a large font and no labels
- [ ] i don't think the UK-WHO to UK90 transition is flagged on the weight chart in the way it is for height
- [ ] the #RoyalColleges3.0 link at the top is hard to see against the background (perhaps deliberately!)

**Comment by eatyourpeas** [comment]
Thank you @statist7 . I have made most of these changes. A few points:

1. issues to do with the form and labelling are an issue with the react client - I will move these issues there and fix in due course. I suspect the difficulty you are having with the datepicker are a problem with the styling library, rather than our client. The datepickers are not intuitive, but if you click on the year, a year picker appears replacing the day/date picker. This may resolve your issue.
2. The preterm data is a bit messy - I have reorganised it now so that the x axis shrinks to render only the measurements and a small domain either side - the only exception is preterm measurements, where the whole range of 23 - 42 weeks is rendered. If no measurements are provided, charts are rendered from 0.0383 to 20 y. We still need a solution for when either term measurements are provided (currently all preterm centiles are rendered) or if multiple data points across the age range including preterm measurements are provided.
3. In the same way that the x axis flexes to max the ages, so the y axis does also. This means that for some measurements (eg the 8y height example), one only gets a small window of the chart which may not be acceptable. 

I will merge the changes I have made here with the main branch and publish to NPM so you can try them out, but I will leave this issue open.

**Comment by eatyourpeas** [comment]
These issues have now been dealt with with pull request #4
