### ISSUE TITLE
Control the Size of plot points

### ISSUE THREAD

**Issue by Sajad321** [rcpch/digital-growth-charts-react-component-library#36]
Hello there,

I am trying to chnage the size of plot points but i didnt find a prop to change it,
Could you add that or tell me how to control it, sometimes its giving very small points ?

**Comment by eatyourpeas** [comment]
Thanks @Sajad321 for getting in touch. Plot point size does not have a prop as they are dynamically sized - if there are several points bunched together as can happen particularly in the neonatal period where babies are weighed sometimes every day, the size changes to allow them to be more easily distinguished one from the other. 
The code for this is on line 572 in CentileChart.tsx
What is the use case? I am open to the idea of changing it but would still need to meet our style standards.
```
if (isChartCrowded) {
        chronData.size = 1.5;
        correctData.size = 1.5;
    } else {
        chronData.size = 3;
        correctData.size = 3;
    }
```

**Comment by Sajad321** [comment]
Thank you for that, but when i zoom out it becomes so small that its not visible as you see in the pictures
the second one is zoomed in and even that sometimes its also small so i was wondering about controlling this behaviour if its already in that line or wish to make an update including this feature

![10_01_2023 05_23_53 م](https://user-images.githubusercontent.com/40560180/211577677-7af40ecc-c61f-47a3-87ca-09d46db92dbf.png)
![10_01_2023 05_23_40 م](https://user-images.githubusercontent.com/40560180/211577688-5dfa7f6c-882c-40bd-ae45-e8a300567151.png)

**Comment by eatyourpeas** [comment]
The default view is to show the data point(s) with some small amount of padding either side. The chart automatically crops to render the datapoints all together. Your second image shows this nicely - both data points to me are an appropriate size for the view - (though somewhat un-life-like - no child will either be that short or that tall at that age most likely, nor exhibit that degree of change). The life course view (which is your first image) was a request from another user but was never part of the basic offer and to my mind has no useful clinical function. Why would you look at a baby or toddler's growth data on a 0-20 y chart? If you plot on paper as much of the UK still does now you would use the infant or low birth weight charts where the scales are different, and have to flip over to the other side to see the older age group. The only reason to have a life course view is for the clinician to show the family where they might end up and toggle back and forth between the two views - this was the use case that was offered originally.

In principle we could have a datapoint that increased in size on hover maybe, but my general feeling is that this is not a priority unless there is a groundswell of opinion from clinicians otherwise.  I will close this for now but happy to revisit (or accept pull requests) if the feedback from users is that this is an important or desirable enhancement. 

Thanks for posting the issue.
