### ISSUE TITLE
extended BMI SDS

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-react-component-library#54]
A suggestion from Mars Skae, endocrinologist is for more SDS lines on the centile charts for children of high BMI
She cites the [CDC](https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cdc.gov%2Fgrowthcharts%2FExtended-BMI-Charts.html&data=05%7C01%7Csimon.chapman%40nhs.net%7Cb310916a48114f656cc008dba9491e5d%7C37c354b285b047f5b22207b48d774ee3%7C0%7C0%7C638289903751707707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K69%2FsEx%2FRYZt7K5a4zEEf1SozETO232QjWsKf5mJpIA%3D&reserved=0)

**Comment by statist7** [comment]
The questions to ask are: which extra SDS lines would they be, and in what circumstances would they be drawn?

The current centiles are spaced 2/3 SDS up to 2 2/3, so it would be plausible to continue on that basis with the same spacing, as 3 1/3 and 4 etc. Another alternative would be to space them more widely at say 2 SDS apart, i.e. at 4 and 6 to match 2, which I think would be better. It would be straightforward to interpolate or extrapolate using the +2 and +4 lines.

In terms of drawing the lines, it would be good to develop an algorithm which drew them when required and not otherwise. This would avoid having to customise the chart. Perhaps when the BMI SDS is sufficiently far above the 99.6th centile it triggers the +4 or even the +6 line being plotted.

**Comment by dc2007git** [comment]
@eatyourpeas is this issue still open for discussion?

**Comment by eatyourpeas** [comment]
Discussion at Project Board 22.8.24
BMI charts should have SDS lines at:
- [x] +2.67 SDS
- [x] +3.33 SDS
- [x] +3.67 SDS
- [x] +4.0 SDS
There is already an API endpoint that can generate custom lines against an SDS, so we can use this for this purpose.

**Comment by eatyourpeas** [comment]
that was implemented some time back so closing here

the original question was about extended BMI SDS but this is something specific to CDC as they have reset the baseline to the 98th centile for children above this to give 99.9 and 99.99th centiles. This is implemented within our CDC BMI offer, but this is not done for UK-WHO.
